### ISSUE TITLE
Issue upon launch when testing 3.7.1

### ISSUE THREAD

**Issue by SpartanOperator** [Skwizzy/SPT-LootingBots#87] opened 2023-10-21 00:55 UTC
Please see img in link below and advise accordingly, I am a little lost as to where to go from here. I have attempted manually changing the values in the .mod file using Notepad++ to no success. 

Many kind thanks in advance. 

https://pasteboard.co/W88PAeiRjSvG.png

**Comment by SpartanOperator** [comment] 2023-10-23 14:15
Left 3 days ago with no response. 

Why ask people to create an account and seek you out on GitHub if you aren't going to receive messages? 

Ive also tried on Discord and the SPT forum with no response. 

Any assistance anywhere with this? Even if it's not from Skwizzy?

**Comment by Skwizzy** [comment] 2023-10-23 14:31
I've been out of town this weekend for a wedding and just got back last night... I reached out to you in discord yesterday and then promptly went to bed. Like I said in discord, I am not able to reproduce this issue using the latest files from the beta release. Please make sure that the NoDiscardLimit files were replaced correctly when you downloaded the beta. The `NoDiscardLimit/src/mod.ts` that you downloaded should match the one seen here https://github.com/Skwizzy/SPT-LootingBots/blob/3.7.1/Build/user/mods/Skwizzy-NoDiscardLimit/src/mod.ts

**Comment by Skwizzy** [comment] 2023-10-26 03:39
As reported in discord "I deleted all old NoDiscardLimit folder and cleaned my temp storage (dont know if that helped) via launcher, and made sure to redownload latest version. All is well now. Many kind thanks." Closing this issue

**Closed by Skwizzy** 2023-10-26 03:39 UTC
